### ISSUE TITLE
Command Line Support

### ISSUE THREAD

**Issue by skibulk** [uwedeportivo/torrentzip#3]
Is it possible to invoke torrentzip from the command line? Also, is it possible to create a zip without any compression?

**Comment by Obiwantje** [comment]
It is not possible to run TZ from the command line, however, there IS already a linux client for TZ available. (specifically at the PD forum: http://forum.pleasuredome.org.uk/index.php?showtopic=23394&page=2 )

creating a normal zip without any compression IS possible, however for TZ this would create NON compliant files (as 

the compression ratio is part of the TZ standard)
